### ISSUE TITLE
Simple scene does not load locally

### ISSUE THREAD

**Issue by aabbtree77** [jagenjo/litescene.js#15]
Thank you for this wonderful code base, but I have the problem loading the "Simple scene" example. I run these codes locally, and to avoid browser problems with CORS I simply use

npm install -g http-server, cd /path/to/light.js, followed by http-server ./

This loads a nice intro page with the sponza scene image and provides three examples to explore:
```
Basic Examples
Simple scene: events are captured manually and only takes advantage of the render engine
Complex scene: using the LS.Player
Loaded scene: loading an existing scene created with WebGLStudio
```

The second and third work fine, a very nice reference to the C64 times. However, the first seems to be broken and with google-chrome F12 I can see the following error message:
```
Uncaught TypeError: Cannot read property 'registerShaderNode' of undefined
    at litescene.js:25660
    at litescene.js:58948
```

The line 255660 is this:
``
LGShaders.registerShaderNode( "light/phong", LGraphShaderPhong );
``

And it is the variable LGShaders that is undefined. It becomes undefined on the line 25571:
``
var LGShaders = LiteGraph.Shaders;
``

The LiteGraph object is nonempty and has a lot of properties, but no .Shaders property, which I cannot seem to locate.

I would appreciate any help/comments/hints to make this run.

**Comment by eparker-adaptive3d** [comment]
I got it to work by copying litegraph.js (and litegraph.min.js) from the webglstudio project to the external/ dir .  If you look at utils/build.sh you can see where it copies using relative paths outside of the project.  I assume litegraph wasn't updated when the build was last run.

**Comment by jagenjo** [comment]
I have to say that Im not mantaining this project any longer. So it is full still of problems.
