### ISSUE TITLE
Go to frame and pause

### ISSUE THREAD

**Issue by Zayco** [jagenjo/litescene.js#17]
Hi, 

In the player, is it possible to go to a specific frame and pause, or a way to just cycle through the frames.

Something like seekToFrame() and seekToNextFrame().

I basically want to:
1. Show first frame and pause
2. Trigger next frame and pause
3. Repeat until last frame.

**Comment by jagenjo** [comment]
Scenes do not have "frames", they are an interactive environment.

Animation do have frames, and you can create a script that changes PlayAnimation component current_time to the time you want.
