### ISSUE TITLE
README's link to Litegl.js is broken

### ISSUE THREAD

**Issue by artob** [jagenjo/litescene.js#3]
The Markdown syntax got mixed up somewhere, resulting in a link that goes to https://github.com/jagenjo/litescene.js/blob/master/litegl (404) instead of https://github.com/jagenjo/litegl.js.

The same applies to other links in the README as well.

See: https://github.com/jagenjo/litescene.js/blame/master/README.md#L14

**Comment by jagenjo** [comment]
True, I was writing the links wrong, I fixed it. Thanks Bendiken :+1:
