### ISSUE TITLE
DebugRenderer.prototype.render - is_selected_callback is not a callback

### ISSUE THREAD

**Issue by AlunAlun** [jagenjo/litescene.js#4]
On line 14975 of LiteScene.js:

```
if(is_selected_callback)
   is_component_selected = is_selected_callback( component );
```

is_selected_callback is not a function, it is an object of type RenderSettings, passed automatically by the LEvent.trigger for afterRenderInstances

If these two lines are commented out, then the DebugRenderer renders okay

**Comment by jagenjo** [comment]
Fixed
