### ISSUE TITLE
Can you help me to understand some properties on Camera? thanks.

### ISSUE THREAD

**Issue by tornadory** [jagenjo/litescene.js#6]
Hi,

right now, I am confused about some private properties of the camera component.

all related with the projection matrix.

I want to change the default camera's projection matrix, but I found that there are not set function for it.

and also there are many private properties with name projection matrix such as:
_projection_matrix
_viewprojection_matrix
_view_matrix
_previous_viewprojection_matrix

can you help to understand them? many thanks for it.

and can you tell me that is there any method to change the camera's projection matrix?

I used  LS.GlobalScene.getCamera()._projection_matrix =*;  but failed, I did not see any changes.

I saw I can use camera.projectionMatrix.elements.set(*matrix); to change the camera's projection matrix in ThreeJS, so I want to know is there any similar method for it?

Thanks in advance!

**Comment by jagenjo** [comment]
The view and the projection matrices are computed from the data in the camera (the fov ,aspect, near, far, etc). This means that if you change it manually it will be overwritten automatically by the system. I will check to see if I can have a way to avoid that happening (like a flag to lock the matrices)

**Comment by jagenjo** [comment]
I just uploaded a new version where the camera has the method setCustomProjectionMatrix
I hope it works for you.

**Comment by tornadory** [comment]
@jagenjo  wow, thanks for your quick answer and solution! I will check it right now.

**Comment by tornadory** [comment]
@jagenjo  It's a pity that I tried it but failed, a error showed 'v is undefined'

do you have example to use it?

actually what I want to do is try to make it work with jsartoolkit.

**Comment by jagenjo** [comment]
ups, there was a bug, Im going to fix it and upload it, sorry, I will let you know

**Comment by jagenjo** [comment]
ok, I fixed it.

Btw, the ThreeJS component works again.

**Comment by tornadory** [comment]
@jagenjo  OK, thank you!
