### ISSUE TITLE
How to load DAE format object via LiteScene/SceneNode?

### ISSUE THREAD

**Issue by tornadory** [jagenjo/litescene.js#8]
Hi, 

In the monitor example, using 

`var node = new LS.SceneNode("monster");`
`node.loadAndSetMesh("monitor.obj");`

can load the OBJ file correctly.

But if I change it to some others like the "*.dae" file, it won't work, nothing showing, so I want to know how to load DAE file (with animation) normally.

thanks a lot!

**Comment by jagenjo** [comment]
DAEs are not meshes but complete scenes. So to load them inside your current scene yout must do this:

```js
LS.ResourcesManager.load("dae_url.DAE", onLoad );

function onLoad(a,b)
{
	LS.GlobalScene.root.addChild(a);
}
```

**Comment by jagenjo** [comment]
I just uploaded a new version that makes it easier.

Now just do ```node.load( your_dae_url );```

**Comment by tornadory** [comment]
@jagenjo  got it, thanks!
